### ISSUE TITLE
DXToday 「フォロー」「コンタクト」必要か

### ISSUE THREAD

**Issue by abesat** [XPagesJP/collabTodayJP#11]
「コンタクト」は適切なメアドに届くならいいのですが、誰に届くか怖いので試していません

**Comment by GuyLocke** [comment]
フォローページのTwitterアカウントはホームページで表示されているTwitterをクリックすれば同じ画面になるので不要と思います。
また、RSSも今はほとんど使われていないので不要かと思います。

コンタクトは送られても誰も対応できないと思いますので不要と思います。

従って、両ページは不要と思います。

**Comment by GuyLocke** [comment]
上記の考えから一時的に「フォロー」と「コンタクト」ページは非表示にしています（リンクを非表示にした）。
