### ISSUE TITLE
DX Today のURLをシェアした時の画像が古い

### ISSUE THREAD

**Issue by KHatanaka** [XPagesJP/collabTodayJP#14]
画像及び文言がコラボレーションToday時代のままとなっている。末尾のFacebookでの例を参照。
下記のmetaタグが原因。

`<meta name="description" content="DX Today - News about IBM DX Solutions">
<meta property="og:image" content="http://collaborationtoday.info/collaborationtoday_icon.png">`

![image](https://user-images.githubusercontent.com/4236873/143485535-49d0e757-cbd6-45b7-8f6b-230cbfd62586.png)

**Comment by GuyLocke** [comment]
Metaタグの画像を差し替えました。
こんな感じ。
![image](https://user-images.githubusercontent.com/2740879/143516126-ddeb079c-4d9d-430e-be28-a44c287fedc3.png)

**Comment by KHatanaka** [comment]
画像はOKですが、メタタグで示した「about IBM DX Solutions」が未修正です。

**Comment by GuyLocke** [comment]
DX Today - News about HCL Digital Solutions
に修正しました。
