### ISSUE TITLE
阿部に削除権限をください

### ISSUE THREAD

**Issue by abesat** [XPagesJP/collabTodayJP#5]
これまで公開できずに残ったままのDuplicate Entriesの数々が消せないまま残っているので（代わりにどなたかが定期的に消してくれるのでも可）
[myDeletionIgnored.pdf](https://github.com/XPagesJP/collabTodayJP/files/5798388/myDeletionIgnored.pdf)

**Comment by GuyLocke** [comment]
Satoru Abeに削除権限を付与しました。
私のアカウントに削除権限を追加してテストしたので問題ないと思いますがご確認願います。
![accessgrant_abe](https://user-images.githubusercontent.com/2740879/104529646-8b089c80-564d-11eb-8c5b-eac0e1d0256b.png)
