### ISSUE TITLE
Typeの拡充。とくに「Volt」を対象にしたものを追加。例えば「アプリケーション開発 - Volt」

### ISSUE THREAD

**Issue by abesat** [XPagesJP/collabTodayJP#6]
ほかに…
・「Nomad」もないけど「モバイル」を使用すれば内容的には足りてるので、今のところ不要
・「Sametime」もないけど、現時点では「Notes/Domino」の一部とみなしている、これはあったほうがいいかも

・「Watson Workspace」「Work Services」は逆に要らなくなった

**Comment by GuyLocke** [comment]
タイプを整理しました。
Domino Volt、Sametimeの追加。
Watson Workspace、Work Serviceの削除を行いました。
